stages:
  - Lint commit messages
  - Tests
  - Build & Publish

jobs:
  include:
    - stage: Lint commit messages
      language: node_js
      node_js: lts/*
      before_install:
        - nvm install lts/*
        - yarn
      script: commitlint-travis
    - stage: Tests
      language: ruby
      before_install: gem install bundler -v '2.1.4'
      rvm: 2.7.2
      script:
        - RAILS_ENV=test bundle exec rake test
        - RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec --color --format doc
      # NOTICE: Handles code coverage reporting to Code Climate
      before_install:
        - gem install bundler -v '1.17.3'
        - curl -L $CC_TEST_REPORTER_URL > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: Build & Publish
      if: branch IN ("master", "beta") AND type != pull_request
      language: node_js
      node_js: lts/*
      before_install:
        - nvm install lts/*
        - yarn
      script: npx semantic-release
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_TOKEN
        gem: forest_liana
        gemspec: forest_liana.gemspec
        on:
          all_branches: true
          condition: [ -f ./.trigger-rubygem-release ]
