sudo: false
language: ruby
before_install:
  - gem install bundler -v '1.17.3'
rvm:
  - 2.3.4
script:
  - RAILS_ENV=test bundle exec rake test
  - RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec --color --format doc
