sudo: false
language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.2.0
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rspec --color --format doc
