stages:
  - Lint commit messages
  - Tests
  - Build & Publish

jobs:
  include:
    - stage: Lint commit messages
      language: node_js
      node_js: lts/*
      before_install:
        - nvm install lts/*
        - yarn
      script: commitlint-travis
    - stage: Tests
      language: ruby
      before_install: gem install bundler -v '1.17.3'
      rvm: 2.3.4
      script:
        - RAILS_ENV=test bundle exec rake test
        - RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec --color --format doc
    - stage: Build & Publish
      if: branch IN ("master", "beta") AND type != pull_request
      language: node_js
      node_js: lts/*
      before_install:
        - nvm install lts/*
        - yarn
      script: npx semantic-release
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_TOKEN
        gem: forest_liana
        gemspec: forest_liana.gemspec
        on:
          all_branches: true
          condition: [ -f ./.trigger-rubygem-release ]
