module ForestLiana
  class PermissionsGetter
    class << PermissionsGetter
      def get_permissions_api_route
        '/liana/v3/permissions'
      end

      def get_permissions_for_rendering(rendering_id)
        begin
          query_parameters = { 'renderingId' => rendering_id }
          api_route = get_permissions_api_route
          response = ForestLiana::ForestApiRequester.get(api_route, query: query_parameters)

          if response.is_a?(Net::HTTPOK)
            JSON.parse(response.body)
          else
            raise "Forest API returned an #{ForestLiana::Errors::HTTPErrorHelper.format(response)}"
          end
        rescue => exception
          FOREST_LOGGER.error 'Cannot retrieve the permissions from the Forest server.'
          FOREST_LOGGER.error 'Which was caused by:'
          ForestLiana::Errors::ExceptionHelper.recursively_print(exception, margin: ' ', is_error: true)
          nil
        end
      end

      def fake_old_response
        {
          "Customer_stripe_cards"=>{
            "collection"=>{
              "list"=>true,
              "show"=>false,
              "create"=>false,
              "update"=>false,
              "delete"=>false,
              "export"=>false,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          },
          "Customer_stripe_invoices"=>{
            "collection"=>{
              "list"=>true,
              "show"=>false,
              "create"=>false,
              "update"=>false,
              "delete"=>false,
              "export"=>false,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          },
          "Customer_stripe_payments"=>{
            "collection"=>{
              "list"=>true,
              "show"=>false,
              "create"=>false,
              "update"=>false,
              "delete"=>false,
              "export"=>false,
              "searchToEdit"=>true
            },
            "actions"=>{
              "Customer_stripe_payments-Refund"=>{
                "allowed"=>false,
                "users"=>nil
              }
            },
            "scope"=>nil
          },
          "Customer"=>{
            "collection"=>{
              "list"=>true,
              "show"=>true,
              "create"=>true,
              "update"=>true,
              "delete"=>true,
              "export"=>true,
              "searchToEdit"=>true
            },
            "actions"=>{
              "Customer-Change@@@password"=>{
                "allowed"=>false,
                "users"=>nil
              },
              "Customer-Mark@@@as@@@Live"=>{
                "allowed"=>false,
                "users"=>nil
              },
              "Customer-Upload@@@Legal@@@Docs"=>{
                "allowed"=>false,
                "users"=>nil
              },
              "Customer-Validate@@@Check"=>{
                "allowed"=>false,
                "users"=>nil
              }
            },
            "scope"=>nil
          },
          "Customer_stripe_bank_accounts"=>{
            "collection"=>{
              "list"=>true,
              "show"=>false,
              "create"=>false,
              "update"=>false,
              "delete"=>false,
              "export"=>false,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          },
          "ActorImage"=>{
            "collection"=>{
              "list"=>true,
              "show"=>true,
              "create"=>true,
              "update"=>true,
              "delete"=>true,
              "export"=>true,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          },
          "Comment"=>{
            "collection"=>{
              "list"=>true,
              "show"=>true,
              "create"=>true,
              "update"=>true,
              "delete"=>true,
              "export"=>true,
              "searchToEdit"=>true
            },
            "actions"=>{
              "Comment-Approve"=>{
                "allowed"=>false,
                "users"=>nil
              },
              "Comment-Disapprove"=>{
                "allowed"=>false,
                "users"=>nil
              }
            },
            "scope"=>nil
          },
          "Country"=>{
            "collection"=>{
              "list"=>true,
              "show"=>true,
              "create"=>true,
              "update"=>true,
              "delete"=>true,
              "export"=>true,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          },
          "Actor"=>{
            "collection"=>{
              "list"=>true,
              "show"=>true,
              "create"=>true,
              "update"=>true,
              "delete"=>true,
              "export"=>true,
              "searchToEdit"=>true
            },
            "actions"=>{
              "Actor-Action@@@1"=>{
                "allowed"=>false,
                "users"=>nil
              },
              "Actor-Action@@@2"=>{
                "allowed"=>false,
                "users"=>nil
              }
            },
            "scope"=>nil
          },
          "Customer_stripe_subscriptions"=>{
            "collection"=>{
              "list"=>true,
              "show"=>false,
              "create"=>false,
              "update"=>false,
              "delete"=>false,
              "export"=>false,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          },
          "Genre"=>{
            "collection"=>{
              "list"=>true,
              "show"=>true,
              "create"=>true,
              "update"=>true,
              "delete"=>true,
              "export"=>true,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          },
          "LegalDoc"=>{
            "collection"=>{
              "list"=>true,
              "show"=>false,
              "create"=>false,
              "update"=>false,
              "delete"=>false,
              "export"=>false,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          },
          "Movie"=>{
            "collection"=>{
              "list"=>true,
              "show"=>true,
              "create"=>true,
              "update"=>true,
              "delete"=>true,
              "export"=>true,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          },
          "Rental"=>{
            "collection"=>{
              "list"=>true,
              "show"=>true,
              "create"=>true,
              "update"=>true,
              "delete"=>true,
              "export"=>true,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          },
          "Search"=>{
            "collection"=>{
              "list"=>true,
              "show"=>true,
              "create"=>true,
              "update"=>true,
              "delete"=>true,
              "export"=>true,
              "searchToEdit"=>true
            },
            "actions"=>{},
            "scope"=>nil
          }
        }
      end

      def fake_new_response
        {
          "Customer_stripe_cards"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>false,
              "addEnabled"=>false,
              "editEnabled"=>false,
              "deleteEnabled"=>false,
              "exportEnabled"=>false
            },
            "actions"=>{}
          },
          "Customer_stripe_invoices"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>false,
              "addEnabled"=>false,
              "editEnabled"=>false,
              "deleteEnabled"=>false,
              "exportEnabled"=>false
            },
            "actions"=>{}
          },
          "Customer_stripe_payments"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>false,
              "addEnabled"=>false,
              "editEnabled"=>false,
              "deleteEnabled"=>false,
              "exportEnabled"=>false
            },
            "actions"=>{
              "Customer_stripe_payments-Refund"=>{
                "triggerEnabled"=>false
              }
            }
          },
          "Customer"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>true,
              "addEnabled"=>true,
              "editEnabled"=>true,
              "deleteEnabled"=>true,
              "exportEnabled"=>true
            },
            "actions"=>{
              "Customer-Change@@@password"=>{
                "triggerEnabled"=>false
              },
              "Customer-Mark@@@as@@@Live"=>{
                "triggerEnabled"=>false
              },
              "Customer-Upload@@@Legal@@@Docs"=>{
                "triggerEnabled"=>false
              },
              "Customer-Validate@@@Check"=>{
                "triggerEnabled"=>false
              }
            }
          },
          "Customer_stripe_bank_accounts"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>false,
              "addEnabled"=>false,
              "editEnabled"=>false,
              "deleteEnabled"=>false,
              "exportEnabled"=>false
            },
            "actions"=>{}
          },
          "ActorImage"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>true,
              "addEnabled"=>true,
              "editEnabled"=>true,
              "deleteEnabled"=>true,
              "exportEnabled"=>true
            },
            "actions"=>{}
          },
          "Comment"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>true,
              "addEnabled"=>true,
              "editEnabled"=>true,
              "deleteEnabled"=>true,
              "exportEnabled"=>true
            },
            "actions"=>{
              "Comment-Approve"=>{
                "triggerEnabled"=>false
              },
              "Comment-Disapprove"=>{
                "triggerEnabled"=>false
              }
            }
          },
          "Country"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>true,
              "addEnabled"=>true,
              "editEnabled"=>true,
              "deleteEnabled"=>true,
              "exportEnabled"=>true
            },
            "actions"=>{}
          },
          "Actor"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>true,
              "addEnabled"=>true,
              "editEnabled"=>true,
              "deleteEnabled"=>true,
              "exportEnabled"=>true
            },
            "actions"=>{
              "Actor-Action@@@1"=>{
                "triggerEnabled"=>false
              },
              "Actor-Action@@@2"=>{
                "triggerEnabled"=>false
              }
            }
          },
          "Customer_stripe_subscriptions"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>false,
              "addEnabled"=>false,
              "editEnabled"=>false,
              "deleteEnabled"=>false,
              "exportEnabled"=>false
            },
            "actions"=>{}
          },
          "Genre"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>true,
              "addEnabled"=>true,
              "editEnabled"=>true,
              "deleteEnabled"=>true,
              "exportEnabled"=>true
            },
            "actions"=>{}
          },
          "LegalDoc"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>false,
              "addEnabled"=>false,
              "editEnabled"=>false,
              "deleteEnabled"=>false,
              "exportEnabled"=>false
            },
            "actions"=>{}
          },
          "Movie"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>true,
              "addEnabled"=>true,
              "editEnabled"=>true,
              "deleteEnabled"=>true,
              "exportEnabled"=>true
            },
            "actions"=>{}
          },
          "Rental"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>true,
              "addEnabled"=>true,
              "editEnabled"=>true,
              "deleteEnabled"=>true,
              "exportEnabled"=>true
            },
            "actions"=>{}
          },
          "Search"=>{
            "collection"=>{
              "browseEnabled"=>true,
              "readEnabled"=>true,
              "addEnabled"=>true,
              "editEnabled"=>true,
              "deleteEnabled"=>true,
              "exportEnabled"=>true
            },
            "actions"=>{}
          },
          "161"=>{
            "Customer_stripe_cards"=>{
              "scope"=>nil
            },
            "Customer_stripe_invoices"=>{
              "scope"=>nil
            },
            "Customer_stripe_payments"=>{
              "scope"=>nil
            },
            "Customer"=>{
              "scope"=>nil
            },
            "Customer_stripe_bank_accounts"=>{
              "scope"=>nil
            },
            "ActorImage"=>{
              "scope"=>nil
            },
            "Comment"=>{
              "scope"=>nil
            },
            "Country"=>{
              "scope"=>nil
            },
            "Actor"=>{
              "scope"=>nil
            },
            "Customer_stripe_subscriptions"=>{
              "scope"=>nil
            },
            "Genre"=>{
              "scope"=>nil
            },
            "LegalDoc"=>{
              "scope"=>nil
            },
            "Movie"=>{
              "scope"=>nil
            },
            "Rental"=>{
              "scope"=>nil
            },
            "Search"=>{
              "scope"=>nil
            }
          }
        }
      end
    end
  end
end
